AppLayout:

<AppLayout>:
    orientation: "vertical"
    BoxLayout:
        orientations: "horizontal"
        size_hint: 1, 0.2
        Label:
            text: "PROB\n0.74"
        Label:
            text: "CLASS\nSwing"
        Label:
            text: "REPS\n0"
    Button:
        text: "Webcam feed here"
    BoxLayout:
        orientation: "horizontal"
        size_hint: 1, 0.2
        Button:
            text: "Start/Stop"
        Button:
            text: "Reset"